test = {   'name': 'q1',
    'points': None,
    'suites': [   {   'cases': [   {   'code': '>>> \n>>> square(1) == 1\nTrue',
                                       'failure_message': '1 ** 2 == 1 because 1 * 1 = 1',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 2,
                                       'success_message': 'Good job!'},
                                   {'code': '>>> square(0) == 0\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> square(2.5) == 6.25\nTrue', 'hidden': True, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
