test = {   'name': 'q2',
    'points': None,
    'suites': [   {   'cases': [   {   'code': '>>> \n>>> import foo\n>>> \n>>> assert("bar") not in dir(foo)\n',
                                       'failure_message': 'capitalization matters!',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> \n>>> import foo\n>>> \n>>> assert("BAR") in dir(foo)\n',
                                       'failure_message': 'make sure you define BAR in foo.py',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> \n>>> import foo\n>>> \n>>> assert foo.BAR == "baz"\n',
                                       'failure_message': 'check the value of foo.BAR',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 1,
                                       'success_message': 'Good job!'}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
