test = {   'name': 'q2',
    'points': None,
    'suites': [   {   'cases': [   {   'code': '>>> \n>>> import subprocess\n>>> \n>>> result = subprocess.run(["python", "foo.py"], capture_output=True)\n>>> result.stdout\nb\'Hello, world!\\n\'',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 1,
                                       'success_message': 'Good job!'}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
